version: 2.1

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:3.2.5-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: 3
          BUNDLER_VERSION: 2.4.19
          RAILS_ENV: test
          CC_TEST_REPORTER_ID: $CC_TEST_REPORTER_ID
          RAILS_MASTER_KEY: $RAILS_MASTER_KEY
      - image: circleci/postgres:13.2
        environment:
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: app-{{ checksum "Gemfile.lock" }}

      - run:
          name: Configure bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      # Yarn install
      - run:
          name: Yarn install
          command: yarn install

      # Bundle install
      - run:
          name: Bundle install
          command: bundle install

      # Store bundle cache
      - save_cache:
          key: app-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Wait for postgres
      - run:
          name: Wait for postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Config database
      - run:
          name: Config database
          environment:
            - RAILS_ENV: test
          command: |
            echo 'test:
              adapter: postgresql
              database: apptestdb
              username: postgres
              password: postgres
              host: localhost
            ' > config/database.yml
      - run:
          name: Setup Database
          command: bundle exec rake db:create db:schema:load --trace

      # Rubocop
      - run:
          name: Run Rubocop
          command: bundle exec rubocop --parallel

      # Brakeman
      - run:
          name: Run Brakeman
          command: bundle exec brakeman

      # Rspec
      - run:
          name: Setup Code Climate Test Reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - run:
          name: Run RSpec
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
          when: always

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter format-coverage -t simplecov $CIRCLE_ARTIFACTS/coverage/.resultset.json
            ./tmp/cc-test-reporter upload-coverage
